site_name: NebulaChat
site_url: https://evader.github.io/umn/
repo_url: https://github.com/evader/umn
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - content.code.copy
nav:
  - Home: index.md
  - Installation: install.md
  - Configuration: config.md
  - Plugins: plugins.md
  - Agents: agents.md
  - API: api.md
  - Prompt Store: prompt_store.md
  - FAQ: faq.md
  - Plugin Dev Guide: dev_plugins.md