name: Auto Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Nebula Release ${{ github.ref }}
        body_path: RELEASE.md
        files: |
          installers/**
          vscode-extension/**
          launch/**
          screenshot.png
          nebula-chat-vsix.zip